### ISSUE TITLE
geodata Guatemala not exists

### ISSUE THREAD

**Issue by epirir** [amcharts/amcharts4-geodata#10]
the country Guatemala is not available in this version.

**Comment by martynasma** [comment]
Fixed in [4.1.8](https://github.com/amcharts/amcharts4-geodata/releases/tag/4.1.8).

## [4.1.8] - 2019-10-23

### Added
- New maps: Guatemala, Lebanon, Paraguay.
- U.S. Congressional Districts maps. Look in `region/usa/congressional`. Use like with prefix `am4geodata_region_usa_congressional_*`. [Usage instructions](https://www.amcharts.com/docs/v4/tutorials/using-us-congressional-districts-maps/).
- New world map: `worldGreatLakes*`. It's a version of a World Map with the Great Lakes cut out, to make them consistent with US/Canada regional maps.
- Translation files to country names in various languages added to `lang` directory. [Usage instructions](https://www.amcharts.com/docs/v4/tutorials/using-map-country-name-translations/).

### Fixed
- Fixed duplicate ids in `russiaCrimea*` maps.
- Updated map of The Netherlans to not include river cutouts.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
