### ISSUE TITLE
Is this the correct republic identifier?

### ISSUE THREAD

**Issue by maksabuzyarov** [amcharts/amcharts4-geodata#15]
Republic "Gorno-Altay" has an id "RU-GA?"

Why is there a question mark?

List of files:
russiaHigh.js
russiaLow.js
russiaCrimeaLow.js
russiaCrimeaHigh.js

**Comment by eleave** [comment]
Hi there!
I was using the russiaCrimeaLow geodata when got some ISO-codes errors, then came here and saw this issue, someone got ahead of me! :D

- Tatarstan: RU-TT code (wrong code), **RU-TA - is correct**
- Gorno-Altay: RU-GA? (wrong code and name), **Altai Republic - RU-GA - is correct**

Source: http://www.geonames.org/RU/administrative-division-.html

**Comment by martynasma** [comment]
OK, so the next update will have these changes:

RU-ALT Altay > RU-ALT Altay Kray (to distinguish from Altay (Republic))
RU-GA? Gorno-Altay > RU-AL Altay
RU-TT Tatarstan > RU-TA Tatarstan

We decided to use "y" instead of "i" to maintain consistency with current naming.

If anyone notice any more errors, or have any justified objections to the above, please speak up :)

**Comment by martynasma** [comment]
Fixed in 4.1.17.

## [4.1.17] - 2020-08-04

### Added
- New maps: Timor-Leste, Trinidad and Tobago, Falkland Islands, Guam, Northern Mariana, Montserrat, Grenada, Martinique, Saint Barthélemy, U.S. Virgin Islands, British Virgin Islands, Guadeloupe, Turks and Caicos Islands, Haiti.

### Fixed
- Fixed some name typos in Malaysian maps.
- Fixed IDs and some names in maps of Russia: ID for Tatarstan; ID and name for Altay (Republic); added "Kray" to Altay Kray to distinguish from the name-sake republic.
- Fixed Polish translation for Myanmar (`lang/PL`).
- Fixed Chile map: Ñuble region was missing.

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
