### ISSUE TITLE
There is an error in Philippines map

### ISSUE THREAD

**Issue by mlab817** [amcharts/amcharts4-geodata#16]
The id for "Cotabato" province is "PH-COM" which is similar to "Compostela Valley". It should be "PH-NCO".

See https://en.wikipedia.org/wiki/ISO_3166-2:PH

**Comment by martynasma** [comment]
Fixed in [4.1.15](https://github.com/amcharts/amcharts4/releases/tag/4.1.15).

## [4.1.15] - 2020-05-08

### Added
- New map `norway2020*` to reflect updated sub-division for Norway. The old version (`norway*`) is still there for backwards compatibility.
- New maps: Montenegro, Iran, South Sundan (two versions: official and unofficial from 2015).

### Fixed
- Fixed minor issues in Virginia County map.
- Fixed ID for Cotabato in map of Phillipines.

[Full change log](https://github.com/amcharts/amcharts4-geodata/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
