### ISSUE TITLE
Chile's  Ñuble Region is missing on chileHigh and chileLow

### ISSUE THREAD

**Issue by hirishh** [amcharts/amcharts4-geodata#20]
Hello,

This region is missing in your chile's geodata 4.1.15. It's a new region created since 5 September 2018. 

Here a codepen of current geomap: https://codepen.io/hirish/pen/zYrvdya
Regions of Chile: https://en.wikipedia.org/wiki/Regions_of_Chile
Region of Ñuble: https://en.wikipedia.org/wiki/%C3%91uble_Region

Best,

hirish

**Comment by martynasma** [comment]
Fixed in 4.1.17.

## [4.1.17] - 2020-08-04

### Added
- New maps: Timor-Leste, Trinidad and Tobago, Falkland Islands, Guam, Northern Mariana, Montserrat, Grenada, Martinique, Saint Barthélemy, U.S. Virgin Islands, British Virgin Islands, Guadeloupe, Turks and Caicos Islands, Haiti.

### Fixed
- Fixed some name typos in Malaysian maps.
- Fixed IDs and some names in maps of Russia: ID for Tatarstan; ID and name for Altay (Republic); added "Kray" to Altay Kray to distinguish from the name-sake republic.
- Fixed Polish translation for Myanmar (`lang/PL`).
- Fixed Chile map: Ñuble region was missing.

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
