### ISSUE TITLE
Geodata for Morelos(morLow,morHigh) have same data with Nuevo Leon(nleLow,nleHigh)

### ISSUE THREAD

**Issue by ImbiRM** [amcharts/amcharts4-geodata#26]
Morelos and Nuevo Leon state both have same data and showing Nuevo Leon

**Comment by martynasma** [comment]
Fixed in 4.1.23

## [4.1.23] - 2022-03-31

### Added
- New map: `regions/world/africaMorocco*` (Moroccan version of the map of Africa).
- New map: `latvia2021*` (updated in 2021 region map for Latvia).
- New map: Taiwan.
- New map: `spainProvinces2*` (same as `spainProvinces*` except with overseas territories moved close to mainland).
- New map: `franceDepartments2*` (mainland + overseas departments).

### Fixed
- Fixed area IDs in map of Slovenia.
- Fixed JSON syntax error in `ugandaLow.json`.
- Added some missing maps to `countries` and `countries2` data files.
- Fixed some name typos in the map of Hungary.
- Fixed names in the map of Chad.
- Fixed Morelos (Mexico) county map.
