### ISSUE TITLE
State Florida from usaLow ("Florida",id:"US-FL") has a wrong shape

### ISSUE THREAD

**Issue by achopijocoder** [amcharts/amcharts4-geodata#6]
State Florida from usaLow ("Florida",id:"US-FL") has a wrong shape

![image](https://user-images.githubusercontent.com/13352070/50342736-a06d7400-0524-11e9-8d22-6f19891945b9.png)

**Comment by martynasma** [comment]
Are you using usaLow.js from our CDN? Or somewhere else?

Florida looks good to me on all our maps:
https://codepen.io/team/amcharts/pen/e43d047864e2b0376c123048b1e8899e?editors=0010

**Comment by achopijocoder** [comment]
I'm using version 4.0.24 from github, can you test it?

**Comment by martynasma** [comment]
I updated my codepen to load the 4.0.24 version of the usaLow.js taken directly from this repo.

https://raw.githubusercontent.com/amcharts/amcharts4-geodata/master/dist/script/usaLow.js

(I uploaded it to CodePen because you can't include directly from github because of http headers)

FL still looks fine:
https://codepen.io/team/amcharts/pen/e43d047864e2b0376c123048b1e8899e?editors=1000

**Comment by achopijocoder** [comment]
Ok! I was taking the Florida state from puerto Rico , Thanks for the help! Closing this.
